apiVersion: v1
kind: Pod
metadata:
  name: evicted-pod
spec:
  containers:
    - name: busybox
      image: busybox
      resources:
        requests:
          memory: "10Gi"
      command: ["sh", "-c", "while true; do echo hello; sleep 10; done"]