apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        memory: "64Mi"
    command: ["sh", "-c", "dd if=/dev/zero of=/dev/null bs=1M count=128"]