---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-error-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-error-agent-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-error-agent-binding
subjects:
  - kind: ServiceAccount
    name: k8s-error-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-error-agent-role
  apiGroup: rbac.authorization.k8s.io